language: node_js
sudo: true
node_js:
  - 10
env:
  - PATH=$HOME/purescript:$PATH
install:
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/v0.12.0/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - npm install -g bower pulp@^12.3.0
  - bower install
script:
  - pulp build
  - pulp test

cache:
  directories:
    - output
